// ?qa=1 시드 샘플 — 스크린샷 QA 기준 화면.
// 병합 4케이스가 모두 나오도록 설계: 수정 블록 2 + 오른쪽 전용(추가) 1 + 왼쪽 전용(삭제) 1, 긴 줄 1.
// 백틱/`${}`가 포함된 코드라 템플릿 리터럴 대신 줄 배열로 보관한다.

export const QA_LEFT = [
  '// DiffDesk QA 샘플 — 재고 계산 모듈 (왼쪽: 원본)',
  'export interface Item {',
  '  id: string',
  '  name: string',
  '  price: number',
  '  stock: number',
  '}',
  '',
  '/** 부가세율 — 2026년 기준 */',
  'const TAX_RATE = 0.1',
  '',
  '// 합계 계산: 오른쪽에서는 reduce 구현으로 바뀐다 (수정 블록)',
  'export function totalPrice(items: Item[]): number {',
  '  let sum = 0',
  '  for (const item of items) {',
  '    sum += item.price * item.stock',
  '  }',
  '  return Math.round(sum * (1 + TAX_RATE))',
  '}',
  '',
  '// 재고 부족 목록: 이 함수는 왼쪽에만 있다 (삭제 블록)',
  'export function lowStock(items: Item[], threshold: number): Item[] {',
  '  return items.filter((item) => item.stock < threshold)',
  '}',
  '',
  'export function formatItem(item: Item): string {',
  '  return `${item.name} x${item.stock}`',
  '}',
  '',
  'export const DEFAULT_ITEMS: Item[] = [',
  "  { id: 'A-001', name: '모니터', price: 320000, stock: 4 },",
  "  { id: 'A-002', name: '키보드', price: 89000, stock: 12 },",
  "  { id: 'A-003', name: '마우스', price: 45000, stock: 30 }",
  ']',
  '',
  '// 긴 줄: 자동 줄바꿈 · 가로 스크롤 · 미니맵 확인용',
  "export const NOTE = '이 문자열은 한 줄이 매우 길 때 에디터의 자동 줄바꿈 토글과 가로 스크롤, 미니맵 표시가 어떻게 동작하는지 확인하기 위한 QA 전용 안내문입니다. 실제 기능과는 무관하며 오로지 길이 확보를 위해 같은 취지의 설명을 한 번 더 반복해 둡니다.'",
  ''
].join('\n')

export const QA_RIGHT = [
  '// DiffDesk QA 샘플 — 재고 계산 모듈 (오른쪽: 대상)',
  'export interface Item {',
  '  id: string',
  '  name: string',
  '  price: number',
  '  stock: number',
  '}',
  '',
  '/** 부가세율 — 2026년 기준 */',
  'const TAX_RATE = 0.1',
  '',
  '// 합계 계산: 오른쪽에서는 reduce 구현으로 바뀐다 (수정 블록)',
  'export function totalPrice(items: Item[]): number {',
  '  const sum = items.reduce((acc, item) => acc + item.price * item.stock, 0)',
  '  return Math.round(sum * (1 + TAX_RATE))',
  '}',
  '',
  'export function formatItem(item: Item): string {',
  '  return `${item.name} x${item.stock}`',
  '}',
  '',
  '// 할인 적용: 이 함수는 오른쪽에만 있다 (추가 블록)',
  'export function applyDiscount(price: number, rate: number): number {',
  '  if (rate < 0 || rate > 1) {',
  "    throw new RangeError('할인율은 0~1 사이여야 합니다')",
  '  }',
  '  return Math.round(price * (1 - rate))',
  '}',
  '',
  'export const DEFAULT_ITEMS: Item[] = [',
  "  { id: 'A-001', name: '모니터', price: 298000, stock: 6 },",
  "  { id: 'A-002', name: '키보드', price: 89000, stock: 12 },",
  "  { id: 'A-003', name: '마우스', price: 45000, stock: 30 }",
  ']',
  '',
  '// 긴 줄: 자동 줄바꿈 · 가로 스크롤 · 미니맵 확인용',
  "export const NOTE = '이 문자열은 한 줄이 매우 길 때 에디터의 자동 줄바꿈 토글과 가로 스크롤, 미니맵 표시가 어떻게 동작하는지 확인하기 위한 QA 전용 안내문입니다. 실제 기능과는 무관하며 오로지 길이 확보를 위해 같은 취지의 설명을 한 번 더 반복해 둡니다.'",
  ''
].join('\n')
